[project]
name = "attendence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.3",
    "flask-wtf>=1.2.2",
    "gunicorn>=25.1.0",
    "wtforms>=3.2.1",
]
